/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedNovedadesRouteImport } from './routes/_authenticated/novedades'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as FirmarTokenRouteImport } from './routes/firmar.$token'
import { Route as AuthenticatedEmpleadosIndexRouteImport } from './routes/_authenticated/empleados.index'
import { Route as AuthenticatedEmpleadosIdRouteImport } from './routes/_authenticated/empleados.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovedadesRoute = AuthenticatedNovedadesRouteImport.update({
  id: '/novedades',
  path: '/novedades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const FirmarTokenRoute = FirmarTokenRouteImport.update({
  id: '/firmar/$token',
  path: '/firmar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEmpleadosIndexRoute =
  AuthenticatedEmpleadosIndexRouteImport.update({
    id: '/empleados/',
    path: '/empleados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpleadosIdRoute =
  AuthenticatedEmpleadosIdRouteImport.update({
    id: '/empleados/$id',
    path: '/empleados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/novedades': typeof AuthenticatedNovedadesRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/firmar/$token': typeof FirmarTokenRoute
  '/empleados/$id': typeof AuthenticatedEmpleadosIdRoute
  '/empleados/': typeof AuthenticatedEmpleadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/novedades': typeof AuthenticatedNovedadesRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/firmar/$token': typeof FirmarTokenRoute
  '/empleados/$id': typeof AuthenticatedEmpleadosIdRoute
  '/empleados': typeof AuthenticatedEmpleadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/novedades': typeof AuthenticatedNovedadesRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/firmar/$token': typeof FirmarTokenRoute
  '/_authenticated/empleados/$id': typeof AuthenticatedEmpleadosIdRoute
  '/_authenticated/empleados/': typeof AuthenticatedEmpleadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracion'
    | '/dashboard'
    | '/documentos'
    | '/novedades'
    | '/reportes'
    | '/firmar/$token'
    | '/empleados/$id'
    | '/empleados/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracion'
    | '/dashboard'
    | '/documentos'
    | '/novedades'
    | '/reportes'
    | '/firmar/$token'
    | '/empleados/$id'
    | '/empleados'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/configuracion'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/novedades'
    | '/_authenticated/reportes'
    | '/firmar/$token'
    | '/_authenticated/empleados/$id'
    | '/_authenticated/empleados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FirmarTokenRoute: typeof FirmarTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novedades': {
      id: '/_authenticated/novedades'
      path: '/novedades'
      fullPath: '/novedades'
      preLoaderRoute: typeof AuthenticatedNovedadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/firmar/$token': {
      id: '/firmar/$token'
      path: '/firmar/$token'
      fullPath: '/firmar/$token'
      preLoaderRoute: typeof FirmarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/empleados/': {
      id: '/_authenticated/empleados/'
      path: '/empleados'
      fullPath: '/empleados/'
      preLoaderRoute: typeof AuthenticatedEmpleadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empleados/$id': {
      id: '/_authenticated/empleados/$id'
      path: '/empleados/$id'
      fullPath: '/empleados/$id'
      preLoaderRoute: typeof AuthenticatedEmpleadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedNovedadesRoute: typeof AuthenticatedNovedadesRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedEmpleadosIdRoute: typeof AuthenticatedEmpleadosIdRoute
  AuthenticatedEmpleadosIndexRoute: typeof AuthenticatedEmpleadosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedNovedadesRoute: AuthenticatedNovedadesRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedEmpleadosIdRoute: AuthenticatedEmpleadosIdRoute,
  AuthenticatedEmpleadosIndexRoute: AuthenticatedEmpleadosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FirmarTokenRoute: FirmarTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
